# Generated by Django 3.0.3 on 2020-04-16 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_chambre', models.CharField(blank=True, max_length=50, null=True)),
                ('nom', models.CharField(max_length=25, unique=True)),
                ('prix', models.FloatField()),
                ('statut', models.CharField(choices=[('L', 'libre'), ('O', 'occupee'), ('I', 'indisponible')], max_length=1)),
                ('maison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maison.Maison')),
            ],
            options={
                'ordering': ['nom'],
                'permissions': (('peut voir chamnbre', 'Peut voir chambre'), ('peut voir detail chamnbre', 'Peut voir  detail chambre')),
            },
        ),
    ]
