# Generated by Django 3.0.3 on 2020-04-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='statut',
            field=models.CharField(choices=[('L', 'Libre'), ('O', 'Occupee'), ('I', 'Indisponible')], max_length=1),
        ),
    ]
