# Generated by Django 3.0.3 on 2020-04-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chambre', '0002_auto_20200425_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='nom',
            field=models.CharField(max_length=25),
        ),
    ]
