# Generated by Django 3.0.3 on 2020-04-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='photo_maison',
            field=models.ImageField(default='img/staff.png', upload_to='img/'),
        ),
    ]
