# Generated by Django 3.0.3 on 2020-04-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200404_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maison',
            name='photo_maison',
            field=models.ImageField(null=True, upload_to='utilisateur_img/'),
        ),
    ]
