# Generated by Django 3.0.3 on 2020-04-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200405_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chambre',
            name='disponible',
        ),
        migrations.AddField(
            model_name='chambre',
            name='statut',
            field=models.CharField(choices=[('L', 'libre'), ('O', 'occupee'), ('I', 'indisponible')], default='eererrr', max_length=1),
            preserve_default=False,
        ),
    ]
