# Generated by Django 3.0.3 on 2020-04-06 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200406_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maison',
            name='photo_maison',
        ),
    ]
