# Generated by Django 3.0.3 on 2020-04-08 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_maison_photo_maison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='chambre_c',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Chambre'),
        ),
    ]
