# Generated by Django 3.0.3 on 2020-04-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200408_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Maison', unique=True),
        ),
    ]
