# Generated by Django 3.0.3 on 2020-04-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200411_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='maison',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Maison'),
        ),
        migrations.AlterField(
            model_name='chambre',
            name='nom',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='maison',
            name='nom_maison',
            field=models.CharField(blank=True, max_length=150, unique=True),
        ),
    ]
