# Generated by Django 3.0.3 on 2020-05-16 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payement', '0001_initial'),
        ('payement_e_e', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payement_e_e',
            name='annee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payement.Annee'),
        ),
        migrations.AlterField(
            model_name='payement_e_e',
            name='mois',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payement.Mois'),
        ),
        migrations.DeleteModel(
            name='Annee',
        ),
        migrations.DeleteModel(
            name='Mois',
        ),
    ]
