# Generated by Django 2.1.2 on 2020-05-22 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contrat', '0002_auto_20200516_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='utilisateur_img/'),
        ),
    ]
