# Generated by Django 3.0.3 on 2020-04-16 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('nom_maison', models.CharField(blank=True, max_length=150, unique=True)),
                ('total_chambre', models.IntegerField()),
                ('quartier', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['nom_maison'],
                'permissions': (('peut voir les maisons', 'Peut voir les maisons'),),
            },
        ),
    ]
